!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  mass: 1.84
  J_xx: 0.05
  J_yy: 0.05
  J_zz: 0.094
  K_v_x: 5
  K_v_y: 5
  K_v_z: 5
  K_w_x: 0.18
  K_w_y: 0.18
  K_w_z: 0.2
  K_w_x_px4: 0.0
  K_w_y_px4: 0.0
  K_w_z_px4: 0.0
  c_KP_r_xx: 0.8
  c_KP_r_yy: 0.8
  c_KP_r_zz: 0.5
  c_KP_t_xx: 25
  c_KP_t_yy: 25
  c_KP_t_zz: 25 
  K0_obs_t: 5.0
  K0_obs_r: 1.0
  
  Kp_w_fx: 1.5
  Ki_w_fx: 3.0
  
  T1_min: 5
  T1_max: 500
  
state: []


# These gains work for interaction with surface with mu = 0.4
