!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  mass: 3.0
  J_xx: 0.29052
  J_yy: 0.291195
  J_zz: 0.3367154
  K_v_x: 20
  K_v_y: 20
  K_v_z: 20
  K_w_x: 0.1
  K_w_y: 0.1
  K_w_z: 0.0
  K_w_x_px4: 0.394
  K_w_y_px4: 0.227
  K_w_z_px4: 0.15
  c_KP_r_xx: 4.5
  c_KP_r_yy: 4.5
  c_KP_r_zz: 2.0
  c_KP_t_xx: 20
  c_KP_t_yy: 20
  c_KP_t_zz: 20
state: []
