!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  J_xx: 0.05097
  J_yy: 0.05027
  J_zz: 0.09434
  K_R_x: 2.5
  K_R_y: 2.5
  K_R_z: 0.5
  K_p_x: 2.3
  K_p_y: 2.3
  K_p_z: 2.3
  K_v_x: 2.8
  K_v_y: 2.8
  K_v_z: 2.8
  K_w_x: 0.15
  K_w_x_px4: 0.03
  K_w_y: 0.15
  K_w_y_px4: 0.02
  K_w_z: 0.2
  K_w_z_px4: 0.26
  approach_pitch: 10.0
  mass: 1.4
state: []
