!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  mass: 2.3
  J_xx: 0.05
  J_yy: 0.05
  J_zz: 0.094
  K_v_x: 12
  K_v_y: 12
  K_v_z: 12
  K_w_x: 0.6
  K_w_y: 0.6
  K_w_z: 0.5
  K_w_x_px4: 0.05
  K_w_y_px4: 0.05
  K_w_z_px4: 0.05
  c_KP_r_xx: 3.5
  c_KP_r_yy: 3.5
  c_KP_r_zz: 5
  c_KP_t_xx: 8.0
  c_KP_t_yy: 8.0
  c_KP_t_zz: 8.0 
state: []
