<?xml version="1.0"?>

<robot name="betaX" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <!--<xacro:property name="namespace" value="$(arg namespace)" />-->
  <xacro:property name="namespace" value="" />
  <xacro:property name="rotor_velocity_slowdown_sim" value="25" />
  <xacro:property name="use_mesh_file" value="true" />
  <xacro:property name="mesh_file" value="package://spc_uav_description/meshes/betaX.stl" />
  <xacro:property name="mass" value="1.73" /> <!-- [kg] -->
  <xacro:property name="body_width" value="0.6" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.22" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.01" /> <!-- [kg] -->
  <xacro:property name="rotor_offset_top" value="0.08" /> <!-- [m] -->
  <xacro:property name="radius_rotor" value="0.1379" /> <!-- [m] -->
  <!-- BetaX 1.0  -->
  <xacro:property name="motor_constant" value="2.031e-5" /> <!-- [kg.m/s^2] -->
  <!-- BetaX 2.0  -->
  <!--<xacro:property name="motor_constant" value="1.24e-05" />  [kg.m/s^2] -->
  <xacro:property name="moment_constant" value="0.0135" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0182" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.0182" /> <!-- [s] -->
    <!-- BetaX 1.0  -->
  <xacro:property name="max_rot_velocity" value="920" /> <!-- [rad/s] -->
    <!-- BetaX 2.0  -->
  <!--<xacro:property name="max_rot_velocity" value="1840" />  [rad/s] -->
  <xacro:property name="sin30" value="0.5" />
  <xacro:property name="cos30" value="0.866025403784" />
  <xacro:property name="tilt_angle" value="0.820305" />
  <xacro:property name="sqrt2" value="1.4142135623730951" />
  <xacro:property name="rotor_drag_coefficient" value="8.94e-07" />
  <xacro:property name="rolling_moment_coefficient" value="1e-06" />
  <xacro:property name="arm_color" value="DarkGrey" />
  
  <xacro:property name="arm_mass" value="0.05" /> <!-- [kg] -->
  <xacro:property name="arm_length" value="0.55" /> <!-- [m] -->
  <xacro:property name="tip_radius" value="0.005" /> <!-- [m] -->

  <!-- Property Blocks -->
  <xacro:property name="body_inertia">
    <inertia ixx="0.05097" ixy="0.0" ixz="0.0" iyy="0.05027" iyz="0.0" izz="0.09434" /> <!-- [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] -->
  </xacro:property>


  <!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
  <xacro:property name="rotor_inertia">
    <xacro:box_inertia x="${radius_rotor}" y="0.015" z="0.003" mass="${mass_rotor}" />
  </xacro:property>

  <!-- Instantiate multirotor_base_macro once -->
  <xacro:multirotor_base_macro
    robot_namespace="${namespace}"
    mass="${mass}"
    body_width="${body_width}"
    body_height="${body_height}"
    use_mesh_file="${use_mesh_file}"
    mesh_file="${mesh_file}"
    >
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>
    <gazebo reference="${namespace}/base_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>
    
<!-- Instantiate rotors -->
  <!-- The layout is:
    Front
    3   5
     \|/
   2- = -1
     / \
    6   4
    Back  
  -->  
  
  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    motor_number="0"
    max_rot_velocity="${max_rot_velocity}"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    use_own_mesh="false"
    mesh=""
    color="Red">
    <origin xyz="-0.03 -0.34 0.03" rpy="${tilt_angle} 0 -1.5708" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>
  
    <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    motor_number="1"
    max_rot_velocity="${max_rot_velocity}"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    use_own_mesh="false"
    mesh=""
    color="Red">
    <origin xyz="-0.03 0.34 0.03" rpy="-${tilt_angle} 0 1.5708" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>
  
  
  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    motor_number="2"
    max_rot_velocity="${max_rot_velocity}"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    use_own_mesh="false"
    mesh=""
    color="Blue">
    <origin xyz="0.31 0.14 0.03" rpy="${tilt_angle} 0 0.523599" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>
  
  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="back_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    motor_number="3"
    max_rot_velocity="${max_rot_velocity}"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    use_own_mesh="false"
    mesh=""
    color="DarkGrey">
    <origin xyz="-0.28 -0.20 0.03" rpy="-${tilt_angle} 0 -2.61799" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>
  
  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    motor_number="4"
    max_rot_velocity="${max_rot_velocity}"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    use_own_mesh="false"
    mesh=""
    color="Blue">
    <origin xyz="0.31 -0.13 0.03" rpy="-${tilt_angle} 0 -0.523599" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  
  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="back_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    motor_number="5"
    max_rot_velocity="${max_rot_velocity}"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    use_own_mesh="false"
    mesh=""
    color="DarkGrey">
    <origin xyz="-0.28 0.20 0.03" rpy="${tilt_angle} 0 2.61799" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>
  
  
    <!-- Instantiate ram_uav "mechanics" -->
  <xacro:include filename="$(find spc_uav_description)/urdf/uav_mech_components.xacro" />
  <!-- Add kiwi arm -->
  <xacro:arm_macro
    robot_namespace="${namespace}"
    name="ef_arm"
    mass="${arm_mass}"
    length="${arm_length-tip_radius}"
    color="${arm_color}"
    parent="${namespace}/base_link"
    >
  </xacro:arm_macro>
  <xacro:force_macro
    robot_namespace="${namespace}"
    length="${arm_length}"
    tip_radius="${tip_radius}"
    color="Red"
    parent="${namespace}/ef_arm"
    >
  </xacro:force_macro>
</robot>
