<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- kiwi arm link -->
    <xacro:macro name="arm_macro" params="robot_namespace name mass length color parent">    
        <link name="${robot_namespace}/${name}">
          <inertial>
            <mass value="${mass-0.01}" />  <!-- [kg] -->
            <origin xyz="${length} 0 0" />
            <inertia ixx="${(mass/12) * (3 * 0.005 * 0.005  + length * length)/2}" ixy="0.0" ixz="0.0" iyy="${(mass * length * length)/2 + mass*length*length}" iyz="0.0" izz="${(mass * length * length)/2 + mass*length*length}" />
          </inertial>      
          <collision>
            <origin xyz="${length/2} 0 0" rpy="0 1.57079 0" />
            <geometry>
              <cylinder radius="0.005" length="${length}"/> <!-- [m] -->
            </geometry>
          </collision>
          <visual>
            <origin xyz="${length/2} 0 0" rpy="0 1.57079 0" />
            <geometry>
              <cylinder radius="0.005" length="${length}"/> <!-- [m] -->
            </geometry>
          </visual>     
        </link>
        
        <joint name="${robot_namespace}/${name}_joint" type="fixed">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <parent link="${parent}" />
          <child link="${robot_namespace}/${name}" />
        </joint>

        <gazebo reference="${robot_namespace}/${name}">          
          <material>Gazebo/${color}</material>
          <collision name='${robot_namespace}/${name}_collision'>            
            <surface>
            <friction>
              <ode>
                 <mu>1</mu>
                 <mu2>1</mu2>
                 <slip1>1</slip1>
                 <slip2>1</slip2>
              </ode>
            </friction>
              <contact>
                <ode>
                  <kp>1e+8</kp>
                  <kd>1</kd>
                  <max_vel>0.0</max_vel>
                  <min_depth>0.001</min_depth>
                </ode>
              </contact>
            </surface>
          </collision>
       </gazebo>
       
  </xacro:macro>
  
  <!-- force_sensor -->
    <xacro:macro name="force_macro" params="robot_namespace length tip_radius color parent">    
        <link name="${robot_namespace}/tip">
          <inertial>
            <mass value="0.01" />  <!-- [kg] -->
            <origin xyz="0 0 0" />
            <inertia ixx="0.1677" ixy="0.0" ixz="0.0" iyy="0.1677" iyz="0.0" izz="0.1677" />
          </inertial>      
          <collision>
            <origin xyz="${tip_radius/2} 0 0" rpy="0 1.57079 0" />
            <geometry>
              <sphere radius="${tip_radius}"/> <!-- [m] -->
            </geometry>
          </collision>
          <visual>
            <origin xyz="${tip_radius/2} 0 0" rpy="0 1.57079 0" />
            <geometry>
              <sphere radius="${tip_radius}"/> <!-- [m] -->
            </geometry>
          </visual>          
        </link>
        
        <joint name="${robot_namespace}/tip_joint" type="fixed">
          <origin xyz="${length-tip_radius} 0 0" rpy="0 0 0" />
          <parent link="${parent}" />
          <child link="${robot_namespace}/tip" />
        </joint>

        <gazebo reference="${robot_namespace}/tip">          
          <material>Gazebo/${color}</material>
          <collision name='${robot_namespace}/$tip_collision'>            
            <surface>
            <friction>
              <ode>
                 <mu>1.16</mu>
                 <mu2>1.16</mu2>
                 <slip1>0</slip1>
                 <slip2>0</slip2>
              </ode>
            </friction>
              <contact>
                <ode>
                  <kp>1e+8</kp>
                  <kd>1</kd>
                  <max_vel>0.0</max_vel>
                  <min_depth>0.001</min_depth>
                </ode>
              </contact>
            </surface>
          </collision>
       </gazebo>
 
        <!--<gazebo reference="${robot_namespace}/tip_joint">
            <provideFeedback value="true"/>
            <disableFixedJointLumping>true</disableFixedJointLumping>
        </gazebo>

    
        <gazebo>
            <plugin name="f3d_controller" filename="libgazebo_ros_f3d.so">
               <alwaysOn>true</alwaysOn>
               <updateRate>50.0</updateRate>
               <bodyName>${robot_namespace}/tip</bodyName>
               <topicName>ground_truth/end_effector/force_torque2</topicName>
            </plugin>    
            <plugin name="FTsensor_controller" filename="libgazebo_ros_ft_sensor.so">
            <robotNamespace>${namespace}</robotNamespace>
               <updateRate>50.0</updateRate>
               <topicName>ground_truth/end_effector/force_torque</topicName>
               <gaussianNoise>0.0</gaussianNoise>
               <jointName>${robot_namespace}/tip_joint</jointName>
            </plugin>    
        </gazebo>-->
       
  </xacro:macro>  
  
    <!-- kiwi link -->
    <xacro:macro name="kiwi_macro" params="name mass arm_length color parent">                    
        <joint name="${name}_joint1" type="revolute">
          <origin xyz="${arm_length} 0 0.005" rpy="0 0 0" />
          <axis xyz="0 1 0"/>
          <parent link="${parent}" />
          <child link="${name}_joint_dummy" />
          <limit upper="0.5" lower="-0.5" effort="9999" velocity="99999" />
        </joint>
        <link name="${name}_joint_dummy">
          <inertial>
            <mass value="${mass*0.01}" />  <!-- [kg] -->
            <origin xyz="0 0 0" />
            <inertia ixx="${(2 * mass * 0.01 * 0.01)/5}" ixy="0.0" ixz="0.0" iyy="${(2 * mass * 0.01 * 0.01)/5}" iyz="0.0" izz="${(2 * mass * 0.01 * 0.01)/5}" />
          </inertial>  
        </link>
        <joint name="${name}_joint2" type="revolute">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <axis xyz="0 0 1"/>
          <parent link="${name}_joint_dummy" />
          <child link="${name}_joint_dummy2" />
          <limit upper="0.5" lower="-0.5" effort="9999" velocity="99999" />
        </joint>
        <link name="${name}_joint_dummy2">
          <inertial>
            <mass value="${mass*0.01}" />  <!-- [kg] -->
            <origin xyz="0 0 0" />
            <inertia ixx="${(2 * mass * 0.01 * 0.01)/5}" ixy="0.0" ixz="0.0" iyy="${(2 * mass * 0.01 * 0.01)/5}" iyz="0.0" izz="${(2 * mass * 0.01 * 0.01)/5}" />
          </inertial>  
        </link>
        <joint name="${name}_joint3" type="revolute">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <axis xyz="1 0 0"/>
          <parent link="${name}_joint_dummy2" />
          <child link="${name}_kiwi" />
          <limit upper="1000.0" lower="-1000.0" effort="-1" velocity="-1" />
          <dynamics damping="0.0" friction="0.0"/>
        </joint>
        <link name="${name}_kiwi">
          <inertial>
            <mass value="${mass}" />  <!-- [kg] -->
            <origin xyz="0.005 0 0" />
            <inertia ixx="${(2 * mass * 0.01)/5}" ixy="0.0" ixz="0.0" iyy="${(2 * mass * 0.01)/5}" iyz="0.0" izz="${(2 * mass * 0.01)/5}" />
          </inertial>      
          <collision>
            <origin xyz="0.005 0 0" rpy="0 1.57079 0" />
            <geometry>
              <cylinder radius="0.05" length="0.005"/> <!-- [m] -->
            </geometry>
          </collision>
          <visual>
            <origin xyz="0.005 0 0" rpy="0 1.57079 0" />
            <geometry>
              <cylinder radius="0.05" length="0.005"/> <!-- [m] -->
            </geometry>
          </visual>     
        </link>
       
       <gazebo reference="${name}_kiwi">          
          <material>Gazebo/${color}</material>
          <collision name='${name}_collision'>            
            <surface>
                <friction>
                  <ode>
                     <mu>1</mu>
                     <mu2>1</mu2>
                     <slip1>1</slip1>
                     <slip2>1</slip2>
                  </ode>
                </friction>
              <contact>
                <ode>
                  <kp>1e+8</kp>
                  <kd>1</kd>
                  <max_vel>0.0</max_vel>
                  <min_depth>0.001</min_depth>
                </ode>
              </contact>
            </surface>
          </collision>
       </gazebo>     
       
       <transmission name="${name}_tran1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${name}_joint1">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="${name}_motor1">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
      
      <transmission name="${name}_tran2">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${name}_joint2">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="${name}_motor2">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>   
  </xacro:macro>  
  
    <!-- landing gear leg link -->
    <xacro:macro name="landinggearleg_macro"
    params="name mass length radius origin parent *inertia">    
    <link name="${name}">
      <inertial>
        <mass value="${mass}" />  <!-- [kg] -->
        <origin xyz="0 0 0" />
        <xacro:insert_block name="inertia" />
      </inertial>      
      <collision>
        <origin xyz="0 0 0" rpy="0 1.57079 0" />
        <geometry>
          <cylinder length="${length}" radius="${radius}" /> <!-- [m] -->
        </geometry>
      </collision>     
    </link>
    <joint name="${name}_joint" type="fixed">
      <origin xyz="${origin}" rpy="0 0 0" />
      <parent link="${parent}" />
      <child link="${name}" />
    </joint>

    <gazebo reference="${name}">
      <collision name='${name}_collision'>
        <surface>
          <friction>
            <ode>
              <mu>1</mu>
              <mu2>1</mu2>
            </ode>
          </friction>
          <contact>
            <ode>
              <kp>1e+8</kp>
              <kd>1</kd>
              <max_vel>0.01</max_vel>
              <min_depth>0.001</min_depth>
            </ode>
          </contact>
        </surface>
      </collision>
   </gazebo>
  </xacro:macro>  
  
  <!-- Landing gear link -->  
  <xacro:macro name="landinggear_macro"
    params="mass parent *inertia">    
    <xacro:landinggearleg_macro
        name="landinggear_leg_left"
        mass="${mass}"
        length="0.3"
        radius="0.01"
        origin="0 -0.165 -0.2175"
        parent="${parent}"
        >
        <xacro:insert_block name="inertia" />
    </xacro:landinggearleg_macro>
    <xacro:landinggearleg_macro
        name="landinggear_leg_right"
        mass="${mass}"
        length="0.3"
        radius="0.01"
        origin="0 0.165 -0.2175"
        parent="${parent}"
        >
        <xacro:insert_block name="inertia" />
    </xacro:landinggearleg_macro>
  </xacro:macro>  
</robot>
