!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  mass: 2
  J_xx: 0.05
  J_yy: 0.05
  J_zz: 0.094
  K_v_x: 10
  K_v_y: 10
  K_v_z: 10
  K_w_x: 0.6
  K_w_y: 0.6
  K_w_z: 0.4
  K_w_x_px4: 0.05
  K_w_y_px4: 0.05
  K_w_z_px4: 0.05
  c_KP_r_xx: 5
  c_KP_r_yy: 5
  c_KP_r_zz: 5
  c_KP_t_xx: 7.5
  c_KP_t_yy: 7.5
  c_KP_t_zz: 7.5 
state: []
